### PR TITLE
Fix #4 and #5

### LINKED ISSUE #4: "_" in project_slug breaks vagrant with virtualbox
If you have an "_" character in your project_slug, it will create an invalid vagrantfile.

```
➜  cass_test vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The hostname set for the VM should only contain letters, numbers,
hyphens or dots. It cannot start with a hyphen or dot.
```

Line 5 seems to be the offending line: 
```config.vm.hostname = "cass_test.local"```

### PR DESCRIPTION
**Pull request by spladug**
These fix #4 and #5.

:eyeglasses: @pacejackson @kjoconnor

### CODE REVIEW

**Comment by pacejackson** [comment]
The code looks fine, but I'm getting  this error when I try to bring up a cookiecutter vagrant box:

```
==> default: Error: python setup.py develop --user returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Test_this/Exec[install app]/returns: change from notrun to 0 failed: python setup.py develop --user returned 1 instead of one of [0]
==> default: Notice: Finished catalog run in 34.54 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

strangely, I don't have that problem in the codebase that I updated to use the cookie cutter files in.

**Comment by spladug** [comment]
Can you get the output of setup.py?

**Comment by pacejackson** [comment]
Will do, I'm testing docker as well.

**Comment by pacejackson** [comment]
Nothing really helpful unfortunately.

```
vagrant@test-this:~/test_this$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
vagrant@test-this:~/test_this$ 
```

**Comment by spladug** [comment]
@pacejackson ah ha! that actually is quite helpful. how now with the latest commit?

**Comment by pacejackson** [comment]
Looks like that did the trick, let me check cassandra.

**Comment by pacejackson** [comment]
🐟  Probably should squash the Cassandra version commits but code LGTM

**Comment by spladug** [comment]
yup, the lower-case commits get squashed before merge. :)

**Comment by kjoconnor** [comment]
🐟

**Comment by spladug** [comment]
d10946e136da3f5223c7fc58659a2574199af662...de6afb73b2416e4b1341ac5f70ae5359c7c04b54

**Pull request closed without merging**
