### PR TITLE
Add HVAC integration

### PR DESCRIPTION
**Pull request by spladug**

### CODE REVIEW

**Comment by pacejackson** [comment]
One issue we ran into when working with Vault is if you want to use the `transit` backend, you have to mount it first.  You only need to do this once after you start vault and the command  will actually return an error if you try to mount it again.  Our solution was to add a post-start script to the upstart file that would wait for vault to start and mount the transit back-end after it starts:

```
post-start script
  export VAULT_ADDR='http://127.0.0.1:8200'

  # When vault is available, mount the /transit backend
  while ! /usr/bin/vault status; do sleep 1; done
  exec /usr/bin/vault mount transit
end script
```

It might make sense to include a comment or some sort of guidance about this either in the baseplate documentation or maybe as a commented out portion of the upstart file here?

**Comment by spladug** [comment]
Hmm. It seems pretty conceptually similar to setting up database schema to me. Maybe make a `create_schema` analog for vault in the cookiecutter?

**Comment by pacejackson** [comment]
That seems reasonable to me.

**Comment by spladug** [comment]
:haircut_man: added schema creation hooks and docker-compose support

**Pull request merged**
