### PR TITLE
Add a makefile that calls setup.py build

### PR DESCRIPTION
**Pull request by spladug**
:eyeglasses: @dellis23 @pacejackson

### CODE REVIEW

**Comment by dellis23** [comment]
🐟  ty!

**Comment by pacejackson** [comment]
🐟 Looks fine to me but I am curious, what actually calls this file?

**Comment by pacejackson** [comment]
Will probably need to add this to the list of things that can specify python vs python3, but that's best done in one swoop imo.

**Comment by spladug** [comment]
4e70ed9a7ff20535b245caca420d8519f16175a4

**Pull request closed without merging**
